title: an awesome title
author: some random guy
email: Why do you care for this
description: > # this means to ignore newlines until "baseurl:"
 This is just an awesome text

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
